config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :items
      resources :categories
      root to: "items#index"
    end
    
    devise_for :users, controllers: {
      :sessions => "users/sessions",
      :registrations => "users/registrations" }

  resources :cart_items
  resources :carts
  resources :items
  resources :categories
  resources :users, only: [:index, :show, :edit, :update]

  # webhooks
  post '/webhooks', to: 'webhooks#create'

  # checkouts
  scope '/checkouts' do
    post 'create', to: 'checkouts#create', as: 'checkouts_create'
    get 'success', to: 'checkouts#success', as: 'checkouts_success'
    get 'cancel', to: 'checkouts#cancel', as: 'checkouts_cancel'
    get 'error', to: 'checkouts#error', as: 'checkouts_error'
  end

  root 'welcome#index'
end

app/views/shared/_button.html.erb
<div class="container-fluid text-center">
<button type="button" class="btn btn-dark btn-lg btn-block">Commander maintenant</button>
<div>

app/views/shared/_flash.html.erb
<div style="display: flex; justify-content: center; align-items: center;">
  <% flash.each do |name, msg| %>
    <div data-controller="flash" role="alert" class="<%= class_for_flash(name)%>">
      <%= msg %>
      <button style="align-items: center; padding: 10px 10px;" type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
  <!-- Footer -->
  <footer class="text-center text-lg-start text-dark">
    <!-- Grid container -->
    <div class="container p-4 pb-0">
      <!-- Section: Links -->
      <section class="">
        <!--Grid row-->
        <div class="row ">
          <hr class="my-3">
          <hr class="w-100 clearfix d-md-none" />

          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">Liens utiles</h6>
            <p>
              <%= link_to'Contactez-nous', page_path('contact') %> 
            </p>
            <p>
              <%= link_to'Recrutement', page_path('recrutement') %> 
            </p>
            <p>
              <%= link_to'À propos', page_path('a-propos') %> 
            </p>
            <p>
              <%= link_to'Presse', page_path('presse') %> 
            </p>
          </div>

          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3 text-dark">
            <h6 class="text-uppercase mb-4 font-weight-bold">Informations légales</h6>
            <p>
              <%= link_to 'Politique de confidentialité', page_path('politique-confidentialite')%> 
            </p>
            <p>
            <%= link_to 'CGV', page_path('conditions-generales-de-vente') %>
            </p>
            <p>
            <%= link_to 'Cookies', page_path('cookies') %>
            </p>
          </div>
          <!-- Grid column -->

          <hr class="w-100 clearfix d-md-none" />

          <!-- Grid column -->
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">Contact</h6>
            <p><i class="fas fa-home mr-3"></i> 2 rue Edmond Rostand</p>
            <p><i class="fas fa-print mr-3"></i> 13006 MARSEILLE</p>
            <p><i class="fas fa-envelope mr-3"></i> info@gmail.com</p>
            <p><i class="fas fa-phone mr-3"></i> 07 67 10 30 14</p>
          </div>

          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">Horaires</h6>
            <p><i class="fas fa-clock mr-3"></i> Lundi au vendredi : 11h30 - 15h30</p>
            <p><i class="fas fa-lock mr-3"></i> Fermé le week-end</p>
          </div>
          <!-- Grid column -->

      </div>
        <!--Grid row-->
      </section>
      <!-- Section: Links -->

      <hr class="my-3">

      <!-- Section: Copyright -->
      <section class="p-3 pt-0">
        <div class="row d-flex align-items-center">
          <!-- Grid column -->
          <div class="col-md-7 col-lg-8 text-center text-md-start">
            <!-- CGV -->
            <div class="p-3">
              <p>Nos réseaux</p>
            </div>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-5 col-lg-4 ml-lg-0 text-center text-dark text-md-end">
            <!-- Facebook -->
            <a
               class="btn btn-outline-light btn-floating m-1 bg-dark"
               role="button"
               href="https://www.facebook.com/dwish.marseille/"
               ><i class="fab fa-facebook-f"></i
              ></a>

            <!-- Instagram -->
            <a
               class="btn btn-outline-light btn-floating m-1 bg-dark"
               role="button"
               href="https://www.instagram.com/dwish.marseille/?hl=en"
               ><i class="fab fa-instagram"></i
              ></a>

            <!-- Google Map -->
            <a
               class="btn btn-outline-light btn-floating m-1 bg-dark"
               role="button"
               href="https://www.google.com/maps/dir//dwish+marseille/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x12c9c134200c577f:0x300df3f88a414a9d?sa=X&ved=2ahUKEwjVrbXKwr3_AhVLTaQEHXkNDhkQ9Rd6BAhJEAU"
               ><i class="fab fa-google"></i
              ></a>

          </div>
          <!-- Grid column -->
        </div>
      </section>
      <!-- Section: Copyright -->
    </div>
    <!-- Grid container -->
  </footer>
  <!-- Footer -->

app/views/shared/_gallery.html.erb
<!-- Gallery -->
<div class="row">
  <div class="col-lg-4 col-md-12 mb-4 mb-lg-0">
    <%= image_tag("https://res.cloudinary.com/dhcqyjeip/image/upload/v1686224787/Dwish/team_dwish_ah9bdh.jpg", class: "w-100 shadow-1-strong rounded mb-4", alt: "The Two Founders") %>

    <%= image_tag("https://res.cloudinary.com/dhcqyjeip/image/upload/v1686148376/Dwish/sandwich_picture_11_ofcm8l.jpg", class: "w-100 shadow-1-strong rounded mb-4", alt: "Make a Dwish slogan") %>
  </div>

  <div class="col-lg-4 mb-4 mb-lg-0">
    <%= image_tag("https://res.cloudinary.com/dhcqyjeip/image/upload/v1686148363/Dwish/sandwich_picture_10_muqp3i.jpg", class: "w-100 shadow-1-strong rounded mb-4", alt: "Sandwich on vacation") %>

    <%= image_tag("https://res.cloudinary.com/dhcqyjeip/image/upload/v1686148201/Dwish/sandwich_picture9_syodqy.jpg", class: "w-100 shadow-1-strong rounded mb-4", alt: "Sandwich on a boat") %>
  </div>

  <div class="col-lg-4 mb-4 mb-lg-0">
    <%= image_tag("https://res.cloudinary.com/dhcqyjeip/image/upload/v1686148121/Dwish/box_picture_1_v9nir0.jpg", class: "w-100 shadow-1-strong rounded mb-4", alt: "Sandwich box") %>

    <%= image_tag("https://res.cloudinary.com/dhcqyjeip/image/upload/v1686147799/Dwish/sandwich_picture1_b3lgsa.jpg", class: "w-100 shadow-1-strong rounded mb-4", alt: "Women Holdig Four Sandwiches") %>
  </div>
</div>
<!-- Gallery -->

app/views/shared/_jumbotron.html.erb
  <!-- Background image -->
  <div
    class="p-5 text-center bg-image rounded shadow-1-strong mb-5"
    style="
      background-image: url('https://res.cloudinary.com/dhcqyjeip/image/upload/t_Sharpened/v1686221958/Dwish/jumbotron_ercwno.jpg');
      height: 500px;
      alt= Dwish jumbotron
    "
  >
    <div class="mask" style="">
      <div class="d-flex justify-content-center align-items-center h-100 rounded">
        <div class="text-white">
          <img src="https://res.cloudinary.com/dhcqyjeip/image/upload/v1686222623/Dwish/logo_d1d49763dffa49a0bd4ec3d2d8b759f2_fduvqv.svg" alt="jumbotron" class="p-5" 
          style="
          filter: brightness(0) invert(1);
          height: 400px;
          width: 400px; 
          alt: Dwish logo"
          />
        </div>
      </div>
    </div>
  </div>
  <!-- Background image -->

app/views/shared/_navbar.html.erb
<!-- Navbar -->
<nav class="navbar navbar-expand-lg bg-white mb-5">
  <!-- Container wrapper -->
  <div class="container-fluid">

    <a class="navbar-brand" href="/">
    <img 
      src="https://res.cloudinary.com/dhcqyjeip/image/upload/v1686220004/Dwish/logo_navbar_hg4azx.svg" 
      alt="Dwish" 
      width="60" 
      height="20">
    </a>

      <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

       <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mt-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Commander", items_path, class:"nav-link" %> 
        </li>   
        <li class="nav-item">      
          <a class="nav-link" href="/traiteur">Traiteur</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/a-propos">A propos</a>
        </li>
      </ul>
      <!-- Left links -->
 
   <!-- Collapsible wrapper -->

     <!-- Right elements -->
    <div class="d-flex align-items-center">
      <% if user_signed_in? %>
        <div class="dropdown">
          <button class="btn btn-dark px-3 me-2 rounded-pill dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Mon compte
          </button>
          <ul class="dropdown-menu">
            <%= link_to "Profil", user_path(current_user), class:"dropdown-item" %>
            <li><hr class="dropdown-divider"></li>
            <%= button_to "Se déconnecter", destroy_user_session_path, method: :delete, class:"dropdown-item" %>
          </ul>
            
          <!--- Shopping Cart Button --->
          <% if cart_count_over_one %>
            <%= render(CartButtonComponent.new(cart_size: cart_count_over_one, icon: "fa fa-shopping-bag", url: cart_path(@cart), style:"btn btn-outline-primary rounded-pill")) %>
          <% end %>
      <% else %>
        <%= button_to "Se connecter", new_user_session_path, class:"btn btn-dark px-3 me-2" %>
        <%= link_to "Créer un compte", new_user_registration_path, class:"btn btn-light me-3" %>
      <% end %>
      </div>
       <!-- Right elements -->
      </div>
    <!-- Collapsible wrapper -->
    </div>
  <!-- Container wrapper -->
 </nav>