config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :items
      resources :categories
      root to: "items#index"
    end
    
    devise_for :users, controllers: {
      :sessions => "users/sessions",
      :registrations => "users/registrations" }

  resources :cart_items
  resources :carts
  resources :items
  resources :categories
  resources :users, only: [:index, :show, :edit, :update]

  # webhooks
  post '/webhooks', to: 'webhooks#create'

  # checkouts
  scope '/checkouts' do
    post 'create', to: 'checkouts#create', as: 'checkouts_create'
    get 'success', to: 'checkouts#success', as: 'checkouts_success'
    get 'cancel', to: 'checkouts#cancel', as: 'checkouts_cancel'
    get 'error', to: 'checkouts#error', as: 'checkouts_error'
  end

  root 'welcome#index'
end

app/models/cart.rb
class Cart < ApplicationRecord
  validates :user_id, presence: true
  enum status: { in_progress: 0, paid: 1, cancelled: 2, expired: 3 }
  validates :status, presence: true
  validates :total_amount, presence: true, numericality: { greater_than_or_equal_to: 0 }

  has_many :cart_items, foreign_key: 'cart_id', class_name: 'CartItem', dependent: :destroy
  has_many :items, through: :cart_items, source: :item
  
  has_many :cart_items, dependent: :destroy
  belongs_to :user
  belongs_to :order, optional: true

  def cart_items_number
    self.cart_items.count
  end 

  def cart_items_array
    self.cart_items
  end

# Hash containing grouped  by item {1=>8, 2=>1, 4=>1} 
  def cart_hash
    self.cart_items.group(:item_id).count
    pp self.cart_items.group(:item_id).count
  end

  def find_cart_items_price(id)
    self.cart_items.find_by(item_id: id).price
    pp self.cart_items.find_by(item_id: id).price
  end

  def total_amount
    cart_items.to_a.sum { |item| item.total_price }
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  before_action :initialize_cart, only: [:show, :update, :destroy]
  
    def index
      @carts = Cart.all
    end

  def show
    @cart = Cart.find(session[:cart_id])
    #test to validate cart is the last one created and belongs to the user
    # if not ,redirected to items_path
    if (current_user.id == @cart.user_id) && (@cart.id == Cart.where(user_id: current_user.id ).last.id)
       @cart_items = @cart.cart_items
       else
        redirect_to items_path, notice: "Désolé, accès non autorisé."
    end    
  end

  def create
    @cart = Cart.new(user_id: @current_user.id, status: "in_progress")
    
    respond_to do |format|
      if @cart.save
        format.html { redirect_to item_url(@cart), notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: cart.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @cart = Cart.find(params[:id])
    
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: cart.errors, status: :unprocessable_entity }
      end
    end

  end
  
  def destroy
    @cart.destroy!

    respond_to do |format|
      format.html { redirect_to items_path, notice: "Cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
private

def initialize_cart
@cart = Cart.find(params[:id]) 
end

def invalid_cart
  logger.error "Attempt to access invalid cart #{params[:id]}"
  redirect_to root_path, notice: "Désolé, panier inexistant."
  
end

def cart_params
  params.require(:cart).permit(:user_id, :status)
end

end

app/helpers/carts_helper.rb
module CartsHelper
  def generate_cart_total_amount
    @total_amount = @cart.cart_items.sum { | item | item.price * item.quantity }
    return @total_amount
  end

  def display_name(id)
    Item.find_by(id: id)&.name
  end 
end

app/views/carts/show.html.erb
<section class="h-100 h-custom">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12">
        <div class="card card-registration card-registration-2" style="border-radius: 15px;">
          <div class="card-body p-0">
            <div class="row g-0">
              <div class="col-lg-8">
                <div class="p-5">
                  <div class="d-flex justify-content-between align-items-center mb-5">
                        <h1 class="fw-bold mb-0 text-black">Votre panier</h1>
                      </div>
                      <hr class="my-4">
                      <div id="empty-cart"></div>
                      <div id="redirect" class="text-center"></div>
                      <% @cart_items.group_by(&:item_name).each do |name, items| %>

                      <div class="row mb-4 d-flex justify-content-between align-items-center">
                        <div class="col-md-2 col-lg-2 col-xl-2">
                          <img src= "<%= items.first.item.image_url %>" alt="<%= items.first.item.name %>" class="img-fluid" height="auto" />
                        </div>

                      <div class="col-md-3 col-lg-3 col-xl-3">
                        <h6 class="text-muted"><%= items.first.item.category.name %></h6>
                        <h6 class="text-black mb-0"><%= items.first.item.name %></h6>
                      </div>

                      <div class="col-md-3 col-md-3 col-md-2 d-flex">
                        <%= button_to cart_item_path(item_id: items.first.item.id), class: "btn btn-link p-2", method: :delete, data: { turbo: false } do %>
                          <i class="fas fa-minus"></i>
                        <% end %>

                        <%= number_field_tag :quantity_total, items.sum(&:quantity), class: "form-control form-control-md text-center", readonly: true %>
                        
                        <%= button_to cart_items_path(item_id: items.first.item.id), class: "btn btn-link p-2", method: :post, data: { turbo: false } do %> 
                          <i class="fas fa-plus"></i>
                        <% end %>
                      </div>

                      <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                        <h6 class="mb-0"><%= items.first.price*(items.count) %> €</h6>
                      </div>

                    </div>
                    <% end %>

                    <hr class="my-4">

                  </div>
                </div>

                <div class="col-lg-4 bg-grey">
                    <div class="p-5">
                      <h3 class="fw-bold mb-5 mt-2 pt-1">Récapitulatif</h3>
                      <hr class="my-4">

                <div class="d-flex justify-content-between mb-4">
                  <h5 class="text">Quantité: <%= @cart.cart_items_number %></h5>
                  <h5> Sous-total: <%= @cart.total_amount %> € </h5>
                </div>
            
                <hr class="my-4">

                    <div class="d-flex justify-content-between mb-5">
                      <h5 class="text-uppercase">Total</h5>
                      <h5><%= @cart.total_amount %> € </h5>
                    </div>

                    <%= button_to "Payer", checkouts_create_path, target: :_blank, class:"btn btn-primary btn-lg btn-block" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<script>
  const cartItems = <%= @cart_items.to_json.html_safe %>;

  if (cartItems.length === 0) {
    const emptyCartMessage = document.createElement("h3");
    const redirectionLink = document.createElement("a");

    emptyCartMessage.classList.add("text-center", "p-5");
    emptyCartMessage.innerHTML = "Votre panier est vide 😕";

    redirectionLink.classList.add("btn", "btn-dark", "btn-lg", "text-center");
    redirectionLink.href = "/items";
    redirectionLink.innerHTML = "Commander";

    const cartMessage = document.getElementById("empty-cart");
    const redirectToItems = document.getElementById("redirect");

    cartMessage.appendChild(emptyCartMessage);
    redirectToItems.appendChild(redirectionLink);
  }
</script>