config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :items
      resources :categories
      root to: "items#index"
    end
    
    devise_for :users, controllers: {
      :sessions => "users/sessions",
      :registrations => "users/registrations" }

  resources :cart_items
  resources :carts
  resources :items
  resources :categories
  resources :users, only: [:index, :show, :edit, :update]

  # webhooks
  post '/webhooks', to: 'webhooks#create'

  # checkouts
  scope '/checkouts' do
    post 'create', to: 'checkouts#create', as: 'checkouts_create'
    get 'success', to: 'checkouts#success', as: 'checkouts_success'
    get 'cancel', to: 'checkouts#cancel', as: 'checkouts_cancel'
    get 'error', to: 'checkouts#error', as: 'checkouts_error'
  end

  root 'welcome#index'
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :categories
  has_many :cart_items, dependent: :destroy
  has_many :carts, through: :cart_items

  validates :name, presence: true
  validates :price, presence: true
  validates :description, presence: true
  #validates :image_url, presence: true   #commenté car bloque le chargement du seed.idem plus bas
  validates :quantity, presence: true
  validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :zelty_id, presence: true


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :initialize_cart 

  # GET /items or /items.json
  def index
    @categories = Category.all.includes(:items)
    @items = Item.all.order(:category_id)
    @items_by_category = @items.group_by(&:category_id)
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy!

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
   
  # Use callbacks to share common setup or constraints between actions.
  def set_item
    @item = Item.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def item_params
    params.fetch(:item, {})
  end
   
  end

app/helpers/items_helper.rb
module ItemsHelper
  include ZeltyService

  # Match category names with category ids

  def retrieve_category_names(categories_data, products_data)

    if categories_data.nil? || products_data.nil?
      raise ArgumentError, "categories_data and products_data cannot be nil"
    end

    puts "categories_data: #{categories_data}"
    puts "products_data: #{products_data}"
    
    category_names = {}

    categories_data.each do |tag|
      category_names[tag["id"]] = tag["name"]
      puts "category_names: #{category_names}"
    end

    @product_category_names = []

    products_data.each do |dish|
      dish["tags"].each do |category_id|
        category_name = category_names[category_id]
        puts "category_name: #{category_name}"
        @product_category_names << { tag_id: category_id, tag_name: category_name } if category_name
        puts "product_category_names: #{@product_category_names}"
      end
    end

    @product_category_names.uniq.sort_by { |category| category[:tag_name] }
    puts "product_category_names: #{@product_category_names}"
  end

  # Filter by category in views
          
end

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/items/_item.html.erb
  <div id="<%= dom_id item %>" style="max-width: 540px;">
    <div class="card-body">

      <h5 class="card-title p-2"><strong><%= item.name %></strong></h5>
      
      <div class="row">
        <div class="col">
          <p class="card-text p-2 lh-lg"><%= item.description %></p>
        </div>
      </div>

      <div class="row">
        <div class="col">
          <p class="card-text p-2"><strong><%= item.price %>€</strong></p>
        </div>
      </div>
    </div>

  </div>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render "form", item: @item %>

<div>
  <%= link_to "Show this item", @item %> |
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/index.html.erb
<div class="justify-content-sm-center mx-2">
  <% @categories.each do |category| %>
    <div class="justify-content-sm-center mx-2">
      <h3><%= category.name %></h3>
    </div>
    <% if @items_by_category[category.id].present? %>
      <% @items_by_category[category.id].each do |item| %>
        <div class="row row-cols-1 row-cols-md-4 row-cols-md-2 g-3 mb-3">
          <div class="col-md-4">
            <img src="<%= item.image_url %>" alt="<%= item.name %>" class="img-fluid" height="auto" />
          </div>
          <div class="col-md-4">
            <%= render item %>
            <div class="p-2">
              <%= button_to "Ajouter au panier", cart_items_path(item_id: item.id), class: "btn btn-info btn-dark", method: :post, data: { turbo: false } %> 
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <p>No items in this category.</p>
    <% end %>
  <% end %>
</div>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @item %>

<div>
  <%= link_to "Edit this item", edit_item_path(@item) %> |
  <%= link_to "Back to items", items_path %>

  <%= button_to "Destroy this item", @item, method: :delete %>
</div>